apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    k8s-app: httpd
    qcloud-app: httpd
  name: httpd
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          creationTimestamp: null
          labels:
            k8s-app: httpd
            qcloud-app: httpd
        spec:
          containers:
          - args:
            - -c
            - "2"
            - -t
            - "30"
            - http://10.215.253.151:8080/
            command:
            - ab
            image: httpd:2.4-alpine
            imagePullPolicy: Always
            name: httpd
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 1Gi
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: qcloudregistrykey
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
